# Generated by Django 4.2.15 on 2024-08-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_traincruise_remove_trainticket_arrival_station_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio_id',
            new_name='a_class',
        ),
        migrations.RemoveField(
            model_name='biometricprofile',
            name='bio_id',
        ),
    ]
