# Generated by Django 4.2.15 on 2024-08-16 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_bio_id_user_a_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now_cruise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.traincruise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
