# Generated by Django 4.2.15 on 2024-08-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_robotprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robotprofile',
            name='now_cruise',
        ),
        migrations.RemoveField(
            model_name='robotprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='trainticket',
            name='train',
        ),
        migrations.RemoveField(
            model_name='trainticket',
            name='user',
        ),
        migrations.AddField(
            model_name='trainticket',
            name='face_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainticket',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainticket',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainticket',
            name='seat_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BiometricProfile',
        ),
        migrations.DeleteModel(
            name='RobotProfile',
        ),
        migrations.DeleteModel(
            name='TrainCruise',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
