version: '3.8'

services:
  web:
    build: .
    command: gunicorn RobotStuartRzd.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: RobotStuartRzd.settings
