# Generated by Django 4.2.15 on 2024-08-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Еда'), ('souvenir', 'Сувенир')], max_length=255),
        ),
    ]
