# Generated by Django 4.2.15 on 2024-08-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
